services:
  mariadb:
    image: mariadb:11.7
    container_name: kicc-demo-mariadb
    network_mode: host
    environment:
      MARIADB_ROOT_PASSWORD: "als@2586"
      MARIADB_DATABASE: "kicc_demo"
      TZ: "Asia/Seoul"
    volumes:
      - kicc_backend_mariadb_data:/var/lib/mysql
  redis:
    image: redis:7.2-alpine
    container_name: kicc-demo-redis
    network_mode: host
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis/users.acl:/usr/local/etc/redis/users.acl:ro

volumes:
  kicc_backend_mariadb_data:
